site_name: BigOS Docs
repo_url: https://github.com/Operacja-System/BigOS
copyright: Copyright © 2025 BigOS

nav:
  - Home: index.md
  - About: about.md
  - Issues: https://github.com/Operacja-System/BigOS/issues

theme:
  name: mkdocs
  color_mode: dark
  nav_style: primary
  user_color_mode_toggle: true
  navigation_depth: 3
  highlightjs: true
  hljs_languages:
    - cmake

plugins:
  - search:
      separator: '[\s\-\.\_]+'

extra_javascript:
  - js/riscvasm.js
