#ifndef _STDBIGOS_ERROR_H_
#define _STDBIGOS_ERROR_H_

typedef enum {
	ERR_NONE = 0,
	ERR_INVALID_ARGUMENT,
	ERR_CRITICAL_INTERNAL_FAILURE,
	ERR_HARDWARE_NOT_COMPATIBLE,
	ERR_ALL_ADDRESS_SPACES_IN_USE,
	ERR_PHYSICAL_MEMORY_FULL,
	ERR_OUT_OF_BOUNDS,
	ERR_INTERNAL_FAILURE,
} error_t;

const char* get_error_msg(error_t err);

#endif //_STDBIGOS_ERROR_H_
