#ifndef _STDBIGOS_ERROR_H_
#define _STDBIGOS_ERROR_H_

typedef enum {
	ERR_NONE = 0,
	ERR_VIRT_MEM_SCHEME_NOT_IMPLEMENTED,
	ERR_VIRT_MEM_SCHEME_NOT_SUPPORTED,
	ERR_ASID_NOT_SUPPORTED,
	ERR_ASID_NOT_VALID,
	ERR_INVALID_PAGE_SIZE,
	ERR_PAGE_TABLE_ALREADY_EXISTS,
	ERR_PAGE_TABLE_DOESNT_EXIST,
	ERR_ALREADY_INITIALIZED,
	ERR_VIRTUAL_MEMORY_NOT_INITIALIZED,
} error_t;

const char* get_error_msg(error_t err);

#endif //_STDBIGOS_ERROR_H_
